### ISSUE TITLE
Update mentorship pages on the Mozilla Wiki

### ISSUE THREAD

**Issue by fayepal** [mozilla/Reps#275]
## Goal: 
Update pages on the wiki related to mentorship to update with Coaching Training and Reps Resources Training

## Related Issues & Links: 
#194 

## Roles:

Responsible:

Accountable:

Supporting:

Consulted:

Informed: 

## Required: 
- [x] https://wiki.mozilla.org/ReMo/Mentors
- [x] https://wiki.mozilla.org/ReMo/Mentors/SelectionProcess
- [x] https://wiki.mozilla.org/ReMo/SOPs/Mentoring
- [x] https://wiki.mozilla.org/ReMo/SOPs/Mentoring/Orientation/Call (owner, Due: Jan 14th) 
- [x] https://wiki.mozilla.org/ReMo/SOPs/Mentoring_Training
- [x] https://wiki.mozilla.org/ReMo/SOPs/Mentoring/Reassigning
- [x] https://wiki.mozilla.org/ReMo/Structure_Governance
- [ ] https://wiki.mozilla.org/ReMo/Webinar

**Comment by fayepal** [comment]
Done with majority of the pages. Need guidance on the Webinar page on where to insert the part where they will be assigned to a mentor.

**Comment by MichaelKohler** [comment]
> Done with majority of the pages. Need guidance on the Webinar page on where to insert the part where they will be assigned to a mentor.

I think that needs more discussion, as we still don't have enough coaches to assign new ones. Looping @Mte90 in here as well as he'll be leading the onboarding.

**Comment by Mte90** [comment]
We need to see if we have to update that page indeed.

**Comment by Mte90** [comment]
@fayetandog this task was completed?
